define([], function() {
    var config = {
        "group": "",
        "appid": "751a43643daa4cd58e757d734f645bcc",
        "theme": "blueTheme",
        "siteTitle": " ",
        "siteBannerImage": "images/ui/banner.jpg",
        "mapTitle": "",
        "mapSnippet": "",
        "mapItemDescription": "",
        "mapLicenseInfo": "Public License",
        "homeHeading": "Dreamgis Demo Maps",
        "homeSnippet": "Historias y Mapas de Colombia - GeoApps & GeoServicios",
        "homeSideHeading": "",
        "homeSideContent": "Demo Map for Dreamgis",
        "footerHeading": "",
        "footerDescription": "",
        "footerLogo": "",
        "footerLogoUrl": "",
        "addThisProfileId": "xa-4f3bf72958320e9e",
        "defaultLayout": "grid",
        "searchString": "",
        "sortField": "numRatings",
        "sortOrder": "asc",
        "searchType": "",
        "mapViewer": "simple",
        "paginationSize": 2,
        "galleryItemsPerPage": 9,
        "showProfileUrl": false,
        "showSocialButtons": false,
        "showFooter": true,
        "showBasemapGallery": true,
        "showArcGISBasemaps": true,
        "basemapsGroup": {},
        "showGroupSearch": true,
        "showGroupSort": true,
        "showMapSearch": true,
        "showLayerToggle": true,
        "showLayoutSwitch": true,
        "showOverviewMap": true,
        "showMoreInfo": false,
        "showPagination": true,
        "showArcGISOnlineButton": false,
        "showLicenseInfo": true,
        "showAttribution": true,
        "showComments": false,
        "showRatings": false,
        "showViews": false,
        "showMobileButtons": true,
        "openGalleryItemsNewWindow": false,
        "bannerBackground": "",
        "proxyUrl": "",
        "sharingurl": "",
        "iosAppUrl": "itms://itunes.apple.com/us/app/arcgis/id379687930?mt=8",
        "androidAppUrl": "https://market.android.com/details?id=com.esri.android.client",
        "pointGraphic": "images/ui/bluepoint-21x25.png",
        "sourceCountry": "USA"
    };
    return config;
});